### ISSUE TITLE
define plugin overriding proccess.env causes issues with node webkit production build 

### ISSUE THREAD

**Issue by allforabit** [HenrikJoreteg/hjs-webpack#109] opened 2015-11-25 16:26 UTC
I had an issue where I could no longer access the environment variables in process after I built a production version of an app for node webkit. I solved the issue by removing the define plugin: 

```
 new webpack.DefinePlugin({
        'process.env': {NODE_ENV: JSON.stringify('production')}
      })
```

This seems to overwrite the process.env variable completely (for node webkit) which I assume isn't the intended behaviour. I'm not sure if there's a way around it other than to removed the plugin.

**Comment by lukekarrys** [comment] 2016-05-31 19:55
I believe this is the intended behavior but it is mostly geared towards web apps where frontend libraries will use `process.env` as a flag for code to be excluded from production builds. This combined with the uglifyjs plugin will do dead code elimination and strip out that code.

I've never used webpack for node-webkit before, so I'm curious if there is anything else that you are putting in your config to tell webpack that you are building for node-webkit? If so, then `hjs-weback` could check for that also and possibly exclude that plugin.

**Comment by HenrikJoreteg** [comment] 2016-07-13 23:00
The define plugin is fairly "simple" in that it doesn't attempt to merge anything just provide a way to define variables as part of the build. I'm going to close this as it's not really an issue of this repo. 

Feel free to re-open if you disagree.

**Closed by HenrikJoreteg** 2016-07-13 23:00 UTC
