### ISSUE TITLE
Error in webpack building

### ISSUE THREAD

**Issue by prakhar1989** [HenrikJoreteg/hjs-webpack#47] opened 2015-07-21 18:25 UTC
Hi @HenrikJoreteg, thank you for this awesome plugin. I found this via your human javascript series and wanted to migrate the slew of webpack code that I had into this. 

Unfortunately, I keep seeing these errors when I run `npm run build`.

```
ERROR in bundle.js from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/Users/asrinivasan/Code/mea-culpa/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:24:21)
    at /Users/asrinivasan/Code/mea-culpa/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:62:23
    at Array.forEach (native)
    at Tapable.<anonymous> (/Users/asrinivasan/Code/mea-culpa/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:44:10)
    at Tapable.next (/Users/asrinivasan/Code/mea-culpa/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Tapable.<anonymous> (/Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:136:4)
    at Tapable.applyPluginsAsync (/Users/asrinivasan/Code/mea-culpa/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.<anonymous> (/Users/asrinivasan/Code/mea-culpa/node_modules/webpack/lib/Compilation.js:559:9)
    at Tapable.next (/Users/asrinivasan/Code/mea-culpa/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/index.js:227:4)
    at Tapable.applyPluginsAsync (/Users/asrinivasan/Code/mea-culpa/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.<anonymous> (/Users/asrinivasan/Code/mea-culpa/node_modules/webpack/lib/Compilation.js:555:8)
    at Tapable.next (/Users/asrinivasan/Code/mea-culpa/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/index.js:193:5)
    at /Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:119:25
    at /Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:24:16
    at ExtractTextPlugin.<anonymous> (/Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/index.js:184:6)
    at /Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:119:25
    at /Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:24:16
    at ExtractTextPlugin.<anonymous> (/Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/index.js:179:8)
    at /Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:110:9)
    at ExtractTextPlugin.<anonymous> (/Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/index.js:155:11)
    at /Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:110:9)
    at ExtractTextPlugin.<anonymous> (/Users/asrinivasan/Code/mea-culpa/node_modules/hjs-webpack/node_modules/extract-text-webpack-plugin/index.js:152:10)
```

Here's how my `package.json` looks - 
```javascript
  "dependencies": {
    "axios": "^0.5.4",
    "express": "^4.13.1",
    "lodash": "^3.10.0",
    "react": "^0.13.3",
    "react-router": "^0.13.3"
  },
  "devDependencies": {
    "autoprefixer-core": "^5.2.1",
    "babel": "^5.8.3",
    "babel-core": "^5.8.3",
    "babel-loader": "^5.3.2",
    "css-loader": "^0.15.3",
    "file-loader": "^0.8.4",
    "hjs-webpack": "^2.11.0",
    "json-loader": "^0.5.2",
    "node-libs-browser": "^0.5.2",
    "postcss-loader": "^0.5.1",
    "react-hot-loader": "^1.2.8",
    "style-loader": "^0.12.3",
    "stylus-loader": "^1.2.1",
    "url-loader": "^0.5.6",
    "webpack": "^1.10.1",
    "webpack-dev-server": "^1.10.1",
    "yeticss": "^7.0.1"
  }
```

To note, I didnt install these manually (my npm version 2.9.0) - I just simply ran - 
```
$ npm install --save-dev hjs-webpack`
```

I also tried various `css-loader` versions as noted [here](https://github.com/webpack/css-loader/issues/84) but to no avail. Any help?

---
Here's my webpack.config (if it helps)
```javascript
var getConfig = require('hjs-webpack');
var isDev = process.env.NODE_ENV !== 'production';

module.exports = getConfig({
    in: 'js/App.js',
    out: 'build',
    isDev: isDev,
    clearBeforeBuild: true,
    html: false,
    output: {
        filename: "bundle.js",
        cssFilename: "styles.min.css"
    }
});
```

**Note: This error is not generated in webpack-dev-server mode**

**Comment by HenrikJoreteg** [comment] 2015-07-22 12:37
Strange, I haven't seen this issue, can you change it to  `html: true` and try it again?

**Comment by prakhar1989** [comment] 2015-07-22 12:41
Just tried. Same issue. Is there something else I can provide that will help you debug?

**Comment by prakhar1989** [comment] 2015-07-22 12:46
The other thing is that in the `dev` mode, although the assets compile correctly, hot-reloading doesn't work. I get an error message saying `This module needs to be fully reloaded`

**Comment by HenrikJoreteg** [comment] 2015-07-22 15:35
Try removing stuff like the output stuff and setting isDev to false explicitly.

**Comment by prakhar1989** [comment] 2015-07-23 13:36
Tried both the combinations. Still getting the issue. Can you try copy/pasting my package.json and see if it's working for you? I believe it's got something to do with the package versions (and not webpack.config.js)

**Comment by HenrikJoreteg** [comment] 2015-07-28 03:36
@prakhar1989 is the project on github? can you just give me access temporarily so i can try just cloning/running it?

**Comment by prakhar1989** [comment] 2015-07-28 04:58
@HenrikJoreteg The project is indeed on [Github](http://github.com/prakhar1989/mea-culpa) but after struggling with configuring hljs-webpack I decided to use the usual webpack config by itself. Not sure if this still will be useful.

**Comment by HenrikJoreteg** [comment] 2015-07-28 05:13
Ok, no worries. I'm gonna close this, if anyone else stumbles across this please re-open this issue.

**Closed by HenrikJoreteg** 2015-07-28 05:13 UTC

**Comment by ph3b** [comment] 2016-06-16 20:16
Hello Henrik!

I've stumbled upon a similar issue. To reproduce:
clone https://github.com/ph3b/Jamf-r and run ```$ npm run build```.
Copy of some of the stacktrace. If you point me in the right direction I can try to fix it myself!
````
ERROR in webapp.1.0.0.js from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/Users/mattiden/Dev/jamfor/webapp/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:24:21)
    at /Users/mattiden/Dev/jamfor/webapp/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:62:23
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/mattiden/Dev/jamfor/webapp/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:44:10)
    at Compilation.next (/Users/mattiden/Dev/jamfor/webapp/node_modules/tapable/lib/Tapable.js:69:14)
    at Compilation.<anonymous> (/Users/mattiden/Dev/jamfor/webapp/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:4)
    at Compilation.applyPluginsAsync (/Users/mattiden/Dev/jamfor/webapp/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/mattiden/Dev/jamfor/webapp/node_modules/webpack/lib/Compilation.js:567:9)
```

**Comment by queicherius** [comment] 2017-03-21 14:08
For reference, for me this was caused by running `NODE_ENV=production webpack -p` and could be fixed by running webpack **without** the `-p` flag.
